config/routes.rb
Jerisa::Application.routes.draw do

  root :to => 'pages#our_story'

  resources :food_orders
  resources :invitations
  resources :properties
  resources :guestbook_entries

  match "/guestbook" => 'guestbook_entries#index'

  ['coming_soon', 'rsvp', 'our_story', 'photos', 'registry', 'contact_us', 'locations', 'accomodations'].each do |page|
    match "/#{page}" => "pages##{page}"
  end
end

app/models/guestbook_entry.rb
class GuestbookEntry < ActiveRecord::Base
end

app/controllers/guestbook_entries_controller.rb
class GuestbookEntriesController < ApplicationController
  before_filter :ensure_signing_allowed, :only => [:new, :edit, :update]

  # GET /guestbook_entries
  # GET /guestbook_entries.json
  def index
    @guestbook_entries = GuestbookEntry.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @guestbook_entries }
    end
  end

  # GET /guestbook_entries/1
  # GET /guestbook_entries/1.json
  def show
    @guestbook_entry = GuestbookEntry.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @guestbook_entry }
    end
  end

  # GET /guestbook_entries/new
  # GET /guestbook_entries/new.json
  def new
    @guestbook_entry = GuestbookEntry.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @guestbook_entry }
    end
  end

  # GET /guestbook_entries/1/edit
  def edit
    @guestbook_entry = GuestbookEntry.find(params[:id])
  end

  # POST /guestbook_entries
  # POST /guestbook_entries.json
  def create
    @guestbook_entry = GuestbookEntry.new(params[:guestbook_entry])

    respond_to do |format|
      if verify_recaptcha(:model => @guestbook_entry) && @guestbook_entry.save
        format.html { redirect_to guestbook_entries_path, notice: 'Guestbook entry was successfully created.' }
        format.json { render json: @guestbook_entry, status: :created, location: @guestbook_entry }
      else
        format.html { render action: "new" }
        format.json { render json: @guestbook_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /guestbook_entries/1
  # PUT /guestbook_entries/1.json
  def update
    @guestbook_entry = GuestbookEntry.find(params[:id])

    respond_to do |format|
      if verify_recaptcha(:model => @guestbook_entry) && @guestbook_entry.update_attributes(params[:guestbook_entry])
        format.html { redirect_to guestbook_entries_path, notice: 'Guestbook entry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @guestbook_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guestbook_entries/1
  # DELETE /guestbook_entries/1.json
  def destroy
    @guestbook_entry = GuestbookEntry.find(params[:id])
    @guestbook_entry.destroy

    respond_to do |format|
      format.html { redirect_to guestbook_entries_url }
      format.json { head :no_content }
    end
  end

private
  def ensure_signing_allowed
    redirect_to guestbook_entries_path unless Property.check("allow-guestbook-signing", "true")
  end
end

app/views/guestbook_entries/_form.html.erb
<%= form_for(@guestbook_entry) do |f| %>
  <% if @guestbook_entry.errors.any? %>
    <div id="error_explanation">
      <h4><%= pluralize(@guestbook_entry.errors.count, "error") %> prohibited this <%= GuestbookEntry.model_name.human %> from being saved:</h4>
      <ul>
      <% @guestbook_entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= recaptcha_tags %>
  </div>
  <div class="actions">
    <%= f.submit "Sign the Guestbook" %>
  </div>
<% end %>

app/views/guestbook_entries/edit.html.erb
<h1>Editing guestbook_entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @guestbook_entry %> |
<%= link_to 'Back', guestbook_entries_path %>

app/views/guestbook_entries/index.html.erb
<h1>Guestbook <small>(<%= pluralize @guestbook_entries.count, 'entry' %>)</small></h1>

<% if Property.check("allow-guestbook-signing", "true") %>
  <p style="float: left;"><%= link_to 'Sign the Guestbook &raquo;'.html_safe, new_guestbook_entry_path, :class => 'button' %></p>
<% end %>

<ul id="guestbook_entries">
<% @guestbook_entries.sort_by(&:created_at).reverse.each do |guestbook_entry| %>
  <li>
    <strong><%= guestbook_entry.name %></strong> says:<br/>
    &#8220;<%= guestbook_entry.body %>&#8221;
    <%#= link_to 'Edit', edit_guestbook_entry_path(guestbook_entry) %>
    <%#= link_to 'Destroy', guestbook_entry, confirm: 'Are you sure?', method: :delete %>
  </li>
<% end %>
</ul>

<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>

app/views/guestbook_entries/new.html.erb
<h1>Sign the Guestbook</h1>

<%= render 'form' %>

<%= link_to 'Back', guestbook_entries_path, :class => 'button' %>

<p>&nbsp;</p>

app/views/guestbook_entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @guestbook_entry.name %>
</p>

<p>
  <b>Body:</b>
  <%= @guestbook_entry.body %>
</p>


<%= link_to 'Edit', edit_guestbook_entry_path(@guestbook_entry) %> |
<%= link_to 'Back', guestbook_entries_path %>