config/routes.rb
Jerisa::Application.routes.draw do

  root :to => 'pages#our_story'

  resources :food_orders
  resources :invitations
  resources :properties
  resources :guestbook_entries

  match "/guestbook" => 'guestbook_entries#index'

  ['coming_soon', 'rsvp', 'our_story', 'photos', 'registry', 'contact_us', 'locations', 'accomodations'].each do |page|
    match "/#{page}" => "pages##{page}"
  end
end

app/models/food_order.rb
class FoodOrder < ActiveRecord::Base
  has_many :attendees
end

app/controllers/food_orders_controller.rb
class FoodOrdersController < ApplicationController
  layout 'admin'
  http_basic_authenticate_with :name => ENV['ADMIN_USERNAME'], :password => ENV['ADMIN_PASSWORD']

  # GET /food_orders
  # GET /food_orders.json
  def index
    @food_orders = FoodOrder.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @food_orders }
    end
  end

  # GET /food_orders/1
  # GET /food_orders/1.json
  def show
    @food_order = FoodOrder.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @food_order }
    end
  end

  # GET /food_orders/new
  # GET /food_orders/new.json
  def new
    @food_order = FoodOrder.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @food_order }
    end
  end

  # GET /food_orders/1/edit
  def edit
    @food_order = FoodOrder.find(params[:id])
  end

  # POST /food_orders
  # POST /food_orders.json
  def create
    @food_order = FoodOrder.new(params[:food_order])

    respond_to do |format|
      if @food_order.save
        format.html { redirect_to @food_order, notice: "#{FoodOrder.model_name.human.capitalize} was successfully created." }
        format.json { render json: @food_order, status: :created, location: @food_order }
      else
        format.html { render action: "new" }
        format.json { render json: @food_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /food_orders/1
  # PUT /food_orders/1.json
  def update
    @food_order = FoodOrder.find(params[:id])

    respond_to do |format|
      if @food_order.update_attributes(params[:food_order])
        format.html { redirect_to @food_order, notice: "#{FoodOrder.model_name.human.capitalize} was successfully updated." }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @food_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /food_orders/1
  # DELETE /food_orders/1.json
  def destroy
    @food_order = FoodOrder.find(params[:id])
    @food_order.destroy

    respond_to do |format|
      format.html { redirect_to food_orders_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/food_orders_helper.rb
module FoodOrdersHelper
end

app/views/food_orders/_form.html.erb
<%= form_for(@food_order) do |f| %>
  <% if @food_order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@food_order.errors.count, "error") %> prohibited this food_order from being saved:</h2>

      <ul>
      <% @food_order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/food_orders/edit.html.erb
<h1>Editing Menu Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @food_order %> |
<%= link_to 'Back', food_orders_path %>

app/views/food_orders/index.html.erb
<h1>Menu</h1>

<%= link_to 'New menu item', new_food_order_path %>

<br/>

<table class="table table-striped">
  <tr>
    <th>Name</th>
    <th># Ordered</th>
    <th>% Ordered</th>
    <th></th>
  </tr>
  <% @food_orders.sort_by(&:name).each do |food_order| %>
    <tr>
      <td><%= link_to food_order.name, food_order %></td>
      <td><%= food_order.attendees.count %></td>
      <td><%= Attendee.count == 0 ? '0.0' : food_order.attendees.count / Attendee.count * 100.0 %>%</td>
      <td>
        <ul>
          <li><%= link_to 'Edit', edit_food_order_path(food_order) %></li>
          <li><%= link_to 'Destroy', food_order, confirm: 'Are you sure?', method: :delete %></li>
        </ul>
      </td>
    </tr>
  <% end %>
</table>

app/views/food_orders/new.html.erb
<h1>New Menu Item</h1>

<%= render 'form' %>

<%= link_to 'Back', food_orders_path %>

app/views/food_orders/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @food_order.name %></h1>

<p>
  <b>Ordered By (<%= @food_order.attendees.count %>)</b></br>
  <ul>
    <% @food_order.attendees.sort_by(&:name).each do |attendee| %>
    <li><%= attendee.name %></li>
    <% end %>
  </ul>
</p>

<%= link_to 'Edit', edit_food_order_path(@food_order) %> |
<%= link_to 'Back', food_orders_path %>