config/routes.rb
Jerisa::Application.routes.draw do

  root :to => 'pages#our_story'

  resources :food_orders
  resources :invitations
  resources :properties
  resources :guestbook_entries

  match "/guestbook" => 'guestbook_entries#index'

  ['coming_soon', 'rsvp', 'our_story', 'photos', 'registry', 'contact_us', 'locations', 'accomodations'].each do |page|
    match "/#{page}" => "pages##{page}"
  end
end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
  has_many :attendees

  accepts_nested_attributes_for :attendees, :allow_destroy => true

  validates_presence_of [:name, :max_attendees]
  validate :number_of_attendees

  def number_of_attendees
    Rails.logger.info "attendees.reject(&:marked_for_destruction?).size => #{attendees.reject(&:marked_for_destruction?).size}"
    unless (attendees.reject(&:marked_for_destruction?).size) <= max_attendees
      errors.add(:attendees, "is limited to #{max_attendees} attendees.")
    end
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  layout 'admin'
  http_basic_authenticate_with :name => ENV['ADMIN_USERNAME'], :password => ENV['ADMIN_PASSWORD'], :except => :update

  # GET /invitations
  # GET /invitations.json
  def index
    @invitations = Invitation.all
    @num_responded = Invitation.where(:responded => true).count

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @invitations }
    end
  end

  # GET /invitations/1
  # GET /invitations/1.json
  def show
    @invitation = Invitation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @invitation }
    end
  end

  # GET /invitations/new
  # GET /invitations/new.json
  def new
    @invitation = Invitation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @invitation }
    end
  end

  # GET /invitations/1/edit
  def edit
    @invitation = Invitation.find(params[:id])
  end

  # POST /invitations
  # POST /invitations.json
  def create
    @invitation = Invitation.new(params[:invitation])

    respond_to do |format|
      if @invitation.save
        format.html { redirect_to @invitation, notice: 'Invitation was successfully created.' }
        format.json { render json: @invitation, status: :created, location: @invitation }
      else
        format.html { render action: "new" }
        format.json { render json: @invitation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /invitations/1
  # PUT /invitations/1.json
  def update
    @invitation = Invitation.find(params[:id])

    respond_to do |format|
      if @invitation.update_attributes(params[:invitation])
        format.html { redirect_to @invitation, notice: 'Invitation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @invitation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invitations/1
  # DELETE /invitations/1.json
  def destroy
    @invitation = Invitation.find(params[:id])
    @invitation.destroy

    respond_to do |format|
      format.html { redirect_to invitations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/views/invitations/_form.html.erb
<%= form_for(@invitation) do |f| %>
  <% if @invitation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invitation.errors.count, "error") %> prohibited this invitation from being saved:</h2>

      <ul>
      <% @invitation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :responded %>
    <%= f.check_box :responded %>
  </div>
  <div class="field">
    <%= f.label :max_attendees %>
    <%= f.number_field :max_attendees %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/invitations/edit.html.erb
<h1>Editing invitation</h1>

<%= render 'form' %>

<%= link_to 'Show', @invitation %> |
<%= link_to 'Back', invitations_path %>

app/views/invitations/index.html.erb
<div id="invitations-app">
<script type="text/x-handlebars">
<h1>Invitations <small>({{Invitations.InvitationsController.filteredContent.length}})</small></h1>

<%= link_to 'New Invitation', new_invitation_path %>

<br/>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>
        {{view Ember.Select contentBinding="Invitations.InvitationsController.respondedFilterOptions"
                            selectionBinding="Invitations.InvitationsController.respondedFilter"
                            optionLabelPath="content.label"
                            optionValuePath="content.value"}}
        <br/>
        Responded
      </th>
      <th>Total guests allowed</th>
      <th>
        {{view Ember.Select contentBinding="Invitations.InvitationsController.attendingFilterOptions"
                            selectionBinding="Invitations.InvitationsController.attendingFilter"
                            optionLabelPath="content.label"
                            optionValuePath="content.value"}}
        <br/>
        Total guests attending
      </th>
      <th></th>
    </tr>
  </thead>
  {{#if Invitations.InvitationsController.filteredContentEmpty}}
    <tr>
      <td colspan="5">No Invitations to browse.</td>
    </tr>
  {{else}}
    {{#collection contentBinding="Invitations.InvitationsController.filteredContent" tagName="tbody"}}
      <td>{{{content.show_link}}}</td>
      <td>{{content.responded}}</td>
      <td>{{content.max_attendees}}</td>
      <td>{{content.num_attendees}}</td>
      <td>
        <ul>
          <li>{{{content.edit_link}}}</li>
          <li>{{{content.destroy_link}}}</li>
        </ul>
      </td>
    {{/collection}}
  {{/if}}
  <tfoot>
    <tr>
      <th></th>
      <th>
        {{Invitations.InvitationsController.numResponded}} / {{Invitations.InvitationsController.filteredContent.length}}
        ({{Invitations.InvitationsController.percentResponded}}%)
      </th>
      <th>{{Invitations.InvitationsController.totalGuestsAllowed}}</th>
      <th>{{Invitations.InvitationsController.numAttendees}}</th>
    </tr>
  </tfoot>
</table>
</script>
</div>

<script>
  var invitations = <%= Invitation.all.map {|invitation|
    {
      :name => invitation.name,
      :responded => t(invitation.responded.to_s),
      :max_attendees => invitation.max_attendees,
      :num_attendees => invitation.attendees.count,
      :show_link => link_to(invitation.name, invitation).html_safe,
      :edit_link => link_to('Edit', edit_invitation_path(invitation)).html_safe,
      :destroy_link => link_to('Destroy', invitation, confirm: 'Are you sure?', method: :delete)
    }
  }.to_json.html_safe %>;
</script>
<%= javascript_include_tag "jquery", "ember.min", "underscore-min", "invitations" %>

app/views/invitations/new.html.erb
<h1>New invitation</h1>

<%= render 'form' %>

<%= link_to 'Back', invitations_path %>

app/views/invitations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @invitation.name %>
</p>

<p>
  <b>Responded:</b>
  <%= @invitation.responded %>
</p>

<p>
  <b>Attendees (<%= @invitation.attendees.count %>)</b><br/>
  <ul>
    <% @invitation.attendees.each do |attendee| %>
    <li><%= attendee.name %> would like <%= attendee.food_order.name.downcase %>.</li>
    <% end %>
  </ul>
</p>

<p>
  <b>Total guests allowed:</b>
  <%= @invitation.max_attendees %>
</p>

<%= link_to 'Edit', edit_invitation_path(@invitation) %> |
<%= link_to 'Back', invitations_path %>